name: Run tests

on: [push]
jobs:
  test1:
    name: Test Case 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Produce actual1.txt output
        run: python find_lowest_number.py test_data/test1_expected.txt actual1.txt
      
      - name: Compare1
        run: diff actual1.txt test_data/test1_expected.txt
        continue-on-error: true

  test2:
    name: Test Case 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Produce actual2.txt output
        run: python find_lowest_number.py test_data/test2_expected.txt actual2.txt
      
      - name: Compare2
        run: diff actual2.txt test_data/test2_expected.txt
        continue-on-error: true

  test3:
    name: Test Case 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Produce actual3.txt output
        run: python find_lowest_number.py test_data/test3_expected.txt actual3.txt
      
      - name: Compare3
        run: diff actual3.txt test_data/test3_expected.txt
        continue-on-error: true
